# Generated by Django 5.1.2 on 2025-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcode',
            name='verification_code',
            field=models.SmallIntegerField(null=True),
        ),
    ]
