# Generated by Django 5.1.2 on 2025-05-16 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='post_pictures'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user_post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='topic',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
