# Generated by Django 5.1.2 on 2025-05-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='topic',
            field=models.CharField(max_length=128),
        ),
    ]
