# Generated by Django 5.1.2 on 2025-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_post_tags_alter_user_post_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='tags',
        ),
        migrations.AddField(
            model_name='user_post',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
