# Generated by Django 5.1.2 on 2025-05-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_post_tags_user_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='post',
        ),
        migrations.AddField(
            model_name='user_post',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.picture'),
        ),
    ]
