# Generated by Django 5.1.2 on 2025-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_picture_post_user_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='picture',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
