# Generated by Django 5.1.2 on 2025-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_post_picture_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='picture',
            field=models.ImageField(upload_to='images/post_images'),
        ),
    ]
