# Generated by Django 5.1.2 on 2025-05-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
