# Generated by Django 5.2 on 2025-05-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_post_like_count_alter_user_post_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='picture',
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_post')),
            ],
        ),
    ]
