# Generated by Django 5.2 on 2025-06-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_post_picture_pictures'),
        ('settings_app', '0016_declinerecommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.profilemodel'),
        ),
    ]
