# Generated by Django 5.2 on 2025-06-13 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='view_count',
        ),
        migrations.AddField(
            model_name='user_post',
            name='views',
            field=models.ManyToManyField(related_name='view_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
