# Generated by Django 5.2 on 2025-06-13 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_user_post_view_count_user_post_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='views',
            field=models.ManyToManyField(null=True, related_name='view_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
