# Generated by Django 5.2 on 2025-06-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='url',
        ),
        migrations.CreateModel(
            name='Url_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_post')),
            ],
        ),
    ]
