# Generated by Django 5.2 on 2025-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_profilemodel_id_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(default='asdasdas', max_length=128, verbose_name='password'),
        ),
    ]
