# Generated by Django 5.2 on 2025-06-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_profilemodel_last_login_profilemodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='password',
        ),
    ]
