# Generated by Django 5.2 on 2025-06-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_alter_profilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
    ]
