# Generated by Django 5.2 on 2025-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='settings_app.profilemodel'),
        ),
    ]
