# Generated by Django 5.2 on 2025-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0010_alter_profilemodel_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friend', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='settings_app.requestmodel'),
        ),
    ]
