# Generated by Django 5.2 on 2025-06-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_requestmodel_profilemodel_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='current_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='friend_id',
            field=models.IntegerField(null=True),
        ),
    ]
