# Generated by Django 5.2 on 2025-06-11 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0013_alter_requestmodel_current_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='current_id',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='received_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='sent_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
