# Generated by Django 5.2 on 2025-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0016_declinerecommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='/../images/account.png', upload_to='images/profile_images/'),
        ),
    ]
