# Generated by Django 5.2 on 2025-06-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsModel',
        ),
    ]
