# Generated by Django 5.2 on 2025-06-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0002_delete_friendsmodel'),
        ('settings_app', '0008_alter_profilemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friends', to='settings_app.profilemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings_app.profilemodel')),
            ],
        ),
    ]
