# Generated by Django 5.2 on 2025-06-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsmodel',
            name='friends',
        ),
    ]
