# Generated by Django 5.2 on 2025-06-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_remove_friendsmodel_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsModel',
        ),
    ]
